name: MARS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        run: sudo apt-get update && sudo apt-get install -y default-jre

      - name: Download MARS
        run: wget -O mars.jar https://github.com/qaisjp/myMARS/releases/download/v2018-10-03/myMARS.jar

      - name: Run all .asm files
        run: |
          find . -name '*.asm' -print | while read asm_file; do
            echo "Running $asm_file"
            java -jar mars.jar nc "$asm_file"
          done
